-- D&C Scale — Supabase schema
-- Run this in Supabase → SQL Editor

-- ============================================================
-- agent_runs
-- Every agent execution: success, error, or running
-- ============================================================

create table if not exists agent_runs (
  id            bigint generated always as identity primary key,
  created_at    timestamptz default now() not null,
  client        text        not null,
  agent         text        not null,
  status        text        not null check (status in ('running', 'success', 'error')),
  summary       text,
  metadata      jsonb       default '{}'::jsonb,
  performance   jsonb       default '{}'::jsonb
);

-- Indexes for dashboard queries
create index if not exists agent_runs_client_idx on agent_runs (client);
create index if not exists agent_runs_agent_idx  on agent_runs (agent);
create index if not exists agent_runs_status_idx on agent_runs (status);
create index if not exists agent_runs_created_idx on agent_runs (created_at desc);

-- ============================================================
-- content_pieces
-- Every content piece generated by Content Creator
-- ============================================================

create table if not exists content_pieces (
  id               bigint generated always as identity primary key,
  created_at       timestamptz default now() not null,
  client           text        not null,
  piece_id         text        not null,               -- e.g. "001", "002"
  piece_type       text        not null,               -- "reel" | "static-ad" | "carousel" | ...
  source           text        not null,               -- "cli" | "strategy-agent" | "consultant-agent" | "dashboard"
  status           text        not null default 'draft' check (status in ('draft', 'produced', 'published', 'archived')),
  objective        text,
  angle            text,
  script_format    text,
  emotional_trigger text,
  platforms        text[]      default '{}',
  video_path       text,
  voice_path       text,
  static_path      text,
  publish_results  jsonb       default '[]'::jsonb,    -- [{ platform, postId, status }]
  metrics          jsonb       default '{}'::jsonb,    -- filled by Social Media Metrics Agent
  unique (client, piece_id)
);

create index if not exists content_pieces_client_idx  on content_pieces (client);
create index if not exists content_pieces_status_idx  on content_pieces (status);
create index if not exists content_pieces_created_idx on content_pieces (created_at desc);

-- ============================================================
-- Row Level Security (RLS)
-- Agents use service_role key — bypass RLS by default.
-- If you want to expose data to a frontend with anon key,
-- enable RLS and add policies per client.
-- ============================================================

-- alter table agent_runs enable row level security;
-- alter table content_pieces enable row level security;
