/**
 * Supabase client — shared across all agents
 *
 * Tables used:
 *   - agent_runs   : every agent execution (success or error)
 *   - content_pieces: content generated by Content Creator
 *
 * Env vars required:
 *   SUPABASE_URL  — https://<project-ref>.supabase.co
 *   SUPABASE_KEY  — service_role key (NOT anon key — agents run server-side)
 */

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_KEY;

function headers() {
  return {
    "Content-Type": "application/json",
    apikey: SUPABASE_KEY,
    Authorization: `Bearer ${SUPABASE_KEY}`,
    Prefer: "return=representation",
  };
}

async function insert(table, row) {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;

  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify(row),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Supabase insert error on ${table}: ${err}`);
  }

  const data = await res.json();
  return Array.isArray(data) ? data[0] : data;
}

async function update(table, match, patch) {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;

  const params = new URLSearchParams(
    Object.entries(match).map(([k, v]) => [k, `eq.${v}`])
  ).toString();

  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${params}`, {
    method: "PATCH",
    headers: headers(),
    body: JSON.stringify(patch),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Supabase update error on ${table}: ${err}`);
  }

  const data = await res.json();
  return Array.isArray(data) ? data[0] : data;
}

// ---------------------------------------------------------------------------
// agent_runs
// ---------------------------------------------------------------------------

/**
 * Log a successful or in-progress agent run.
 *
 * @param {string} client        - Client slug (e.g. "dmancuello")
 * @param {string} agent         - Agent name (e.g. "content-creator")
 * @param {"success"|"error"|"running"} status
 * @param {string} summary       - Short human-readable description
 * @param {Object} [metadata]    - Agent-specific structured data
 * @param {Object} [performance] - { duration_ms, tokens_used, ... }
 * @returns {Promise<Object|null>} Inserted row (null if Supabase not configured)
 */
export async function logAgentRun(client, agent, status, summary, metadata = {}, performance = {}) {
  try {
    return await insert("agent_runs", {
      client,
      agent,
      status,
      summary,
      metadata,
      performance,
    });
  } catch (err) {
    console.warn(`[supabase] logAgentRun failed (non-fatal): ${err.message}`);
    return null;
  }
}

/**
 * Log an agent error.
 *
 * @param {string} client
 * @param {string} agent
 * @param {Error}  error
 * @param {Object} [metadata]
 * @returns {Promise<Object|null>}
 */
export async function logAgentError(client, agent, error, metadata = {}) {
  try {
    return await insert("agent_runs", {
      client,
      agent,
      status: "error",
      summary: error.message,
      metadata: { ...metadata, stack: error.stack?.split("\n").slice(0, 5).join("\n") },
      performance: {},
    });
  } catch (err) {
    console.warn(`[supabase] logAgentError failed (non-fatal): ${err.message}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// content_pieces
// ---------------------------------------------------------------------------

/**
 * Register a new content piece generated by Content Creator.
 *
 * @param {Object} piece
 * @param {string} piece.client
 * @param {string} piece.piece_id       - e.g. "001"
 * @param {string} piece.piece_type     - "reel" | "static-ad" | ...
 * @param {string} piece.source         - "cli" | "strategy-agent" | ...
 * @param {string} [piece.objective]
 * @param {string} [piece.angle]
 * @param {string} [piece.script_format]
 * @param {string} [piece.emotional_trigger]
 * @param {string[]} [piece.platforms]
 * @param {string} [piece.video_path]
 * @param {string} [piece.voice_path]
 * @param {string} [piece.static_path]
 * @param {Object[]} [piece.publish_results]
 * @returns {Promise<Object|null>}
 */
export async function registerContentPiece(piece) {
  try {
    return await insert("content_pieces", {
      ...piece,
      status: "draft",
    });
  } catch (err) {
    console.warn(`[supabase] registerContentPiece failed (non-fatal): ${err.message}`);
    return null;
  }
}

/**
 * Update content piece status and/or metrics after publishing or evaluation.
 *
 * @param {string} client
 * @param {string} pieceId
 * @param {Object} patch   - Fields to update (status, metrics, publish_results, etc.)
 * @returns {Promise<Object|null>}
 */
export async function updateContentPiece(client, pieceId, patch) {
  try {
    return await update("content_pieces", { client, piece_id: pieceId }, patch);
  } catch (err) {
    console.warn(`[supabase] updateContentPiece failed (non-fatal): ${err.message}`);
    return null;
  }
}
