/**
 * Supabase client — shared across all agents
 *
 * Tables used:
 *   - agent_runs    : every agent execution (success, error, running)
 *   - agent_outputs : structured deliverables the dashboard renders
 *   - content_pieces: content generated by Content Creator
 *   - notifications : push items for the dashboard bell
 *
 * Env vars required:
 *   SUPABASE_URL  — https://<project-ref>.supabase.co
 *   SUPABASE_KEY  — service_role key (NOT anon key — agents run server-side)
 */

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_KEY;

function headers() {
  return {
    "Content-Type": "application/json",
    apikey: SUPABASE_KEY,
    Authorization: `Bearer ${SUPABASE_KEY}`,
    Prefer: "return=representation",
  };
}

async function insert(table, row) {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;

  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify(row),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Supabase insert error on ${table}: ${err}`);
  }

  const data = await res.json();
  return Array.isArray(data) ? data[0] : data;
}

async function selectMany(table, match = {}, columns = "*", options = {}) {
  if (!SUPABASE_URL || !SUPABASE_KEY) return [];

  const entries = [
    ...Object.entries(match).map(([k, v]) => [k, `eq.${v}`]),
    ["select", columns],
  ];
  if (options.order) entries.push(["order", options.order]);
  if (options.limit) entries.push(["limit", String(options.limit)]);

  const params = new URLSearchParams(entries).toString();

  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${params}`, {
    method: "GET",
    headers: headers(),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Supabase select-many error on ${table}: ${err}`);
  }

  return await res.json();
}

async function upsert(table, rows, onConflict) {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;

  const params = onConflict
    ? `?on_conflict=${encodeURIComponent(onConflict)}`
    : "";

  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}${params}`, {
    method: "POST",
    headers: {
      ...headers(),
      Prefer: "return=representation,resolution=merge-duplicates",
    },
    body: JSON.stringify(rows),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Supabase upsert error on ${table}: ${err}`);
  }

  return await res.json();
}

async function selectOne(table, match, columns = "*") {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;

  const params = new URLSearchParams([
    ...Object.entries(match).map(([k, v]) => [k, `eq.${v}`]),
    ["select", columns],
    ["limit", "1"],
  ]).toString();

  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${params}`, {
    method: "GET",
    headers: headers(),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Supabase select error on ${table}: ${err}`);
  }

  const data = await res.json();
  return Array.isArray(data) ? data[0] ?? null : data;
}

async function update(table, match, patch) {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;

  const params = new URLSearchParams(
    Object.entries(match).map(([k, v]) => [k, `eq.${v}`])
  ).toString();

  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${params}`, {
    method: "PATCH",
    headers: headers(),
    body: JSON.stringify(patch),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Supabase update error on ${table}: ${err}`);
  }

  const data = await res.json();
  return Array.isArray(data) ? data[0] : data;
}

// ---------------------------------------------------------------------------
// generic helpers (exported for agents that need read/write beyond the curated API)
// ---------------------------------------------------------------------------

/** Select many rows. `match` is an AND-joined eq filter. */
export async function select(table, match = {}, columns = "*", options = {}) {
  try {
    return await selectMany(table, match, columns, options);
  } catch (err) {
    console.warn(`[supabase] select failed (non-fatal): ${err.message}`);
    return [];
  }
}

/**
 * Upsert rows. `onConflict` should match a unique constraint (e.g.
 * "client,dimension,value"). Returns the upserted rows or null on failure.
 */
export async function upsertRows(table, rows, onConflict) {
  try {
    return await upsert(table, rows, onConflict);
  } catch (err) {
    console.warn(`[supabase] upsertRows failed (non-fatal): ${err.message}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// clients (read-only convenience)
// ---------------------------------------------------------------------------

/**
 * Fetch a client row from the dashboard schema. Returns null if missing or if
 * Supabase isn't configured. Used by agents that need sector/modules/phase.
 *
 * @param {string} clientId
 * @returns {Promise<Object|null>}
 */
export async function fetchClient(clientId) {
  if (!clientId) return null;
  try {
    return await selectOne(
      "clients",
      { id: clientId },
      "id,name,sector,type,phase,method,fee,modules"
    );
  } catch (err) {
    console.warn(`[supabase] fetchClient failed (non-fatal): ${err.message}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// agent_runs
// ---------------------------------------------------------------------------

/**
 * Log a successful or in-progress agent run.
 *
 * @param {string} client        - Client slug (e.g. "dmancuello")
 * @param {string} agent         - Agent name (e.g. "content-creator")
 * @param {"success"|"error"|"running"} status
 * @param {string} summary       - Short human-readable description
 * @param {Object} [metadata]    - Agent-specific structured data
 * @param {Object} [performance] - { duration_ms, tokens_used, ... }
 * @returns {Promise<Object|null>} Inserted row (null if Supabase not configured)
 */
export async function logAgentRun(client, agent, status, summary, metadata = {}, performance = {}) {
  try {
    return await insert("agent_runs", {
      client,
      agent,
      status,
      summary,
      metadata,
      performance,
    });
  } catch (err) {
    console.warn(`[supabase] logAgentRun failed (non-fatal): ${err.message}`);
    return null;
  }
}

/**
 * Log an agent error.
 *
 * @param {string} client
 * @param {string} agent
 * @param {Error}  error
 * @param {Object} [metadata]
 * @returns {Promise<Object|null>}
 */
export async function logAgentError(client, agent, error, metadata = {}) {
  try {
    return await insert("agent_runs", {
      client,
      agent,
      status: "error",
      summary: error.message,
      metadata: { ...metadata, stack: error.stack?.split("\n").slice(0, 5).join("\n") },
      performance: {},
    });
  } catch (err) {
    console.warn(`[supabase] logAgentError failed (non-fatal): ${err.message}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// content_pieces
// ---------------------------------------------------------------------------

/**
 * Register a new content piece generated by Content Creator.
 *
 * @param {Object} piece
 * @param {string} piece.client
 * @param {string} piece.piece_id       - e.g. "001"
 * @param {string} piece.piece_type     - "reel" | "static-ad" | ...
 * @param {string} piece.source         - "cli" | "strategy-agent" | ...
 * @param {string} [piece.objective]
 * @param {string} [piece.angle]
 * @param {string} [piece.script_format]
 * @param {string} [piece.emotional_trigger]
 * @param {string[]} [piece.platforms]
 * @param {string} [piece.video_path]
 * @param {string} [piece.voice_path]
 * @param {string} [piece.static_path]
 * @param {Object[]} [piece.publish_results]
 * @returns {Promise<Object|null>}
 */
export async function registerContentPiece(piece) {
  try {
    return await insert("content_pieces", {
      ...piece,
      status: "draft",
    });
  } catch (err) {
    console.warn(`[supabase] registerContentPiece failed (non-fatal): ${err.message}`);
    return null;
  }
}

/**
 * Update content piece status and/or metrics after publishing or evaluation.
 *
 * @param {string} client
 * @param {string} pieceId
 * @param {Object} patch   - Fields to update (status, metrics, publish_results, etc.)
 * @returns {Promise<Object|null>}
 */
export async function updateContentPiece(client, pieceId, patch) {
  try {
    return await update("content_pieces", { client, piece_id: pieceId }, patch);
  } catch (err) {
    console.warn(`[supabase] updateContentPiece failed (non-fatal): ${err.message}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// agent_runs (lifecycle updates)
// ---------------------------------------------------------------------------

/**
 * Patch an existing agent_runs row by id. Used to close a run that was
 * opened with status 'running' (typical when the dashboard dispatches an agent).
 *
 * @param {number|string} runId
 * @param {Object} patch  - { status, summary, summary_md, metadata, performance, updated_at }
 * @returns {Promise<Object|null>}
 */
export async function updateAgentRun(runId, patch) {
  if (runId == null) return null;
  try {
    const merged = { updated_at: new Date().toISOString(), ...patch };
    return await update("agent_runs", { id: runId }, merged);
  } catch (err) {
    console.warn(`[supabase] updateAgentRun failed (non-fatal): ${err.message}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// agent_outputs
// ---------------------------------------------------------------------------

/**
 * Register a structured output produced by an agent run. The dashboard reads
 * this table to render reports, content pieces, diagnostics, etc.
 *
 * @param {number|string|null} runId  - agent_runs.id this output belongs to (nullable)
 * @param {string} client
 * @param {string} agent
 * @param {Object} output
 * @param {string} output.output_type  - "report" | "content-piece" | "diagnostic" | ...
 * @param {string} [output.title]
 * @param {string} [output.body_md]    - Human-readable markdown rendered by the dashboard
 * @param {Object} [output.structured] - Agent-specific JSON payload
 * @returns {Promise<Object|null>}
 */
export async function registerAgentOutput(runId, client, agent, output) {
  try {
    return await insert("agent_outputs", {
      run_id: runId ?? null,
      client,
      agent,
      output_type: output.output_type,
      title: output.title ?? null,
      body_md: output.body_md ?? null,
      structured: output.structured ?? {},
    });
  } catch (err) {
    console.warn(`[supabase] registerAgentOutput failed (non-fatal): ${err.message}`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// notifications
// ---------------------------------------------------------------------------

/**
 * Push a notification to the dashboard bell. Replaces Telegram as the primary
 * channel for agent-to-user messages.
 *
 * @param {string} client
 * @param {"info"|"success"|"warning"|"error"} level
 * @param {string} title
 * @param {string} [body]
 * @param {Object} [opts]
 * @param {string} [opts.agent]
 * @param {string} [opts.link] - Deep link the dashboard should navigate to
 * @returns {Promise<Object|null>}
 */
export async function pushNotification(client, level, title, body, opts = {}) {
  try {
    return await insert("notifications", {
      client,
      agent: opts.agent ?? null,
      level,
      title,
      body: body ?? null,
      link: opts.link ?? null,
    });
  } catch (err) {
    console.warn(`[supabase] pushNotification failed (non-fatal): ${err.message}`);
    return null;
  }
}
